### ISSUE TITLE
Add husky pre-push hook

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#132]
Add a husky pre-push hook that prevents pushing if the branch has one of the following:
- Failed tests
- Linting errors

**Comment by christian-bromann** [comment]
@degrammer please have a look at my PR. I left it with just checking Eslint because I feel like adding unit test to the pre commit hook could slow down ones workflow and is sometimes not needed, e.g. if there are changes to the readme or other parts of the code base that aren't impacted by unit tests. That said, I think we can be always smarter what we want to do and this could be a good start.

**Comment by christian-bromann** [comment]
Merged, so closing.
