### ISSUE TITLE
Support for lsp intelligence in cells

### ISSUE THREAD

**Issue by v217** [stateful/vscode-runme#184]
For example with the redhat.vscode-yaml extension a yaml cell in my markdown file would profit from autocompletion, linting etc... from the preconfigured language specific extensions.

**Comment by sourishkrout** [comment]
@mxsdev between the deserializer and the guesslang model Runme might be too overly eager to bias cells to be either shell or markdown. Technically one should be able to change a cell's languageId by clicking on it. Please work through this end-to-end and let's see what you find.

**Comment by mxsdev** [comment]
@sourishkrout 

Did some investigation. To implement this feature, it unfortunately looks like we'd need changes to both the external (go) and internal (de)serializers. For more details:

There is a mismatch between our internal language Ids and those used by VSCode. The reason why you cannot change the `languageId`, for example, is a direct result of this mismatch. I can go far more in-depth here describing the problem - just let me know. Looks to me like we'd want to build a translation/compatibility between "executor" Id (which is the serialized id) and VSCode's "languageId" to solve this problem. I don't think this would require any changes to the runme kernel/service.

Moreover, as I understand it, runme is built on the assumption that code blocks are runnable using an internally defined executor. If the code's language is not compatible, we make it a markdown cell with a fenced codeblock. Fenced Markdown codeblocks do not appear to support LSP (I think VSCode only supports one LSP per text document). To support YAML (non-runnable codeblocks) as code-cells, we would probably need to re-think this approach - in particular, I'm guessing we'd need to redesign some parts of the serializer.

I also don't think the guesslang stuff is causing the root issue here. Rather, it is probably a symptom of the same aforementioned mismatch of language identifiers, since the language identifiers used by the guesslang engine are not consistent with VSCode's. Of course, even if guesslang identifies "yaml," it may not end up in a code-cell, since it's not a supported executor - right?

Let me know how you want to go forward with this. I can give more technical details if you'd like!

**Comment by sourishkrout** [comment]
> There is a mismatch between our internal language Ids and those used by VSCode. The reason why you cannot change the `languageId`, for example, is a direct result of this mismatch. I can go far more in-depth here describing the problem - just let me know. Looks to me like we'd want to build a translation/compatibility between "executor" Id (which is the serialized id) and VSCode's "languageId" to solve this problem. I don't think this would require any changes to the runme kernel/service.

You have some concrete examples here just so I I can understand better?

**Comment by sourishkrout** [comment]
> Moreover, as I understand it, runme is built on the assumption that code blocks are runnable using an internally defined executor. If the code's language is not compatible, we make it a markdown cell with a fenced codeblock. Fenced Markdown codeblocks do not appear to support LSP (I think VSCode only supports one LSP per text document). To support YAML (non-runnable codeblocks) as code-cells, we would probably need to re-think this approach - in particular, I'm guessing we'd need to redesign some parts of the serializer.

I do remember how this works. Making this work is definitely not a trivial fix.

**Comment by mxsdev** [comment]
> You have some concrete examples of the languageId mismatch just so I I can understand better?

The main point of issue is `controller.supportedLanguages` in `kernel.ts`. This expects a list of VSCode `languageId`. Since everything in the array (`bash`, `sh`, `deno`, `vercel`) is not a valid VSCode `languageId`, it shows you no options when you try to select a language.

If, for example, you pass `shellscript` to this array, then it will indeed allow you to select that language from the list. However, this is then liable to serialize the codeblock as language `shellscript` on save, rather than `bash` or `sh`.

So, then, it would seem we would need some kind of layer in between `shellscript` and `bash`/`sh`. Unfortunately in this particular case, it is not 1-1, so there's even more complexity there 😵‍💫

**Comment by v217** [comment]
Hi!
Thanks for the feedback!
I would like to use the [extension and lsp for yaml by redhat](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml&ssr=false#overview) (to get https://json-schema.org/ autocompletion, linting and validation in yaml code fences.) Right now I can't choose yaml as language only shell-code. Thanks!
