### ISSUE TITLE
Achieve legacy-extension execution parity

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#212]
- [x] Curl-ing img (last cell in `examples/README.md`) with notebook-native png renderer crash-hangs
- [x] Cat-ing LICENSE (in `examples/README.md`) does not work
- [x] Run `background=true` as background tasks
- [x] User-prompts (UI) for ENV variables
- [x] Unify cmds/script prep?
- [ ] Deep integrations: Vercel/deno (not priority)
- [ ] Terminal dimensions (not priority)

**Comment by sourishkrout** [comment]
heads up @mxsdev, added `Run background=true as background tasks`.

**Comment by mxsdev** [comment]
@sourishkrout 

Are you having problems with background tasks? The basic one from the example `README.md` works for me; generally, it should be covered by the following line:

```typescript
    taskExecution.isBackground = background
    taskExecution.presentationOptions = {
      focus: true,
      reveal: background ? TaskRevealKind.Never : TaskRevealKind.Always,
      panel: background ? TaskPanelKind.Dedicated : TaskPanelKind.Shared
    }
```

**Comment by sourishkrout** [comment]
> @sourishkrout
> 
> Are you having problems with background tasks? The basic one from the example `README.md` works for me; generally, it should be covered by the following line:
> 
> ```ts
>     taskExecution.isBackground = background
>     taskExecution.presentationOptions = {
>       focus: true,
>       reveal: background ? TaskRevealKind.Never : TaskRevealKind.Always,
>       panel: background ? TaskPanelKind.Dedicated : TaskPanelKind.Shared
>     }
> ```

Just tested again, it appears to block the notebook UI, as the stop button shows indefinitely and the cell execution continues. There is some custom logic in the old runner where it will move on after 2sec (unless non-zero error code). I believe that UI portion is missing.

**Comment by mxsdev** [comment]
@sourishkrout 

Was able to solve this issue, but while solving it, I uncovered another bug: ordinarily, we would identify the terminal based on its `RUNME_ID` variable set in the `env` property of CreationOptions. Since this new terminal is created as a `CustomExecution`, that `env` property never gets set, and it is unclear how to identify the created terminal.

I originally thought I could use the `pty` property, but bafflingly, that property is not populated with the active Pseudoterminal.

Struggled with this for a while, still unsure how to go about solving it. I added this problem to the list in PR as well 👍
