### ISSUE TITLE
Stable release published to Open-VSX?

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#422]
The log seems empty under the respective step's section: https://github.com/stateful/vscode-runme/actions/runs/4633048523/jobs/8197836621

The version on https://open-vsx.org/extension/stateful/runme seems to be stuck on v0.7.x.

**Comment by degrammer** [comment]
The GitHub action does not support --target, issue created https://github.com/HaaLeo/publish-vscode-extension/issues/37
one alternative is to use ovsx directly, I've been trying it here https://github.com/stateful/vscode-runme/blob/fix-openvsx-publish/.github/scripts/openvsxPublish.js

**Comment by sourishkrout** [comment]
Made some progress https://github.com/eclipse/openvsx/issues/731 @degrammer.

**Comment by degrammer** [comment]
Thank you! @sourishkrout  so it seems this has two blockers:
1. It seems to publish to open-vsx from the API has some restrictions due to a max payload issue? since we switched to platform specific targets, the extension size double 50%, from 4.75 mb to ~11.8 mb
2. We may want to contribute to the [GitHub action](https://github.com/HaaLeo/publish-vscode-extension/issues/37) to support multiple platforms via target, blocked by 1

**Comment by sourishkrout** [comment]
Hopefully, they'll respond quickly to this https://github.com/EclipseFdn/open-vsx.org/issues/1812. Probably want to wait for it.

**Comment by sourishkrout** [comment]
@degrammer let's follow up on the third party issues.

**Comment by degrammer** [comment]
We have a duplicated namespace issue, reported here https://github.com/EclipseFdn/open-vsx.org/issues/877#issuecomment-1551886323

**Comment by sourishkrout** [comment]
This is finally fixed! Namespace and extension are back 💪! https://open-vsx.org/extension/stateful/runme
