### ISSUE TITLE
Identify test automation (e2e, smoke tests, etc) opportunities

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#55]
- Broke out in separate issue: stateful/runme#58
- [x] Explore leveraging wdio for e2e & smoke tests  stateful/runme#59
- [x] Add baseline functional test suite
- [x] Run unit tests in C/I: https://github.com/stateful/runme.dev/issues/40

**Comment by christian-bromann** [comment]
> [ ] Explore leveraging wdio for e2e & smoke tests

see https://github.com/stateful/vscode-runme/pull/59

**Comment by christian-bromann** [comment]
> * Add baseline functional test suite

With https://github.com/stateful/vscode-runme/pull/59 I added a basic check that ensures that the Readme is loaded and a cell can be executed. I would be careful adding more concrete tests for now as I believe their value is limited due to the fact that we might change a lot of the features moving on. Let me know if you want to have any concrete examples be tested and I can create separate issues for them.
