### ISSUE TITLE
`vscode-runme` fails to start in VSCode built on Electron 25

### ISSUE THREAD

**Issue by zhouxinghong** [stateful/vscode-runme#734]
Hello friends!
`vscode-runme` fails to start in VSCode built on Electron 25.
VSCode 
`https://az764295.vo.msecnd.net/exploration/a7703202794cf4894003d6502eb196192e8e0333/VSCodeUserSetup-x64-1.81.0-exploration.exe`
Windows10
1.9.1690573644

**Comment by christian-bromann** [comment]
@zhouxinghong thanks for raising the issue.

Can you explain more how you have installed VS Code? Is this a special version of VS Code?

**Comment by zhouxinghong** [comment]
This is the next generation of VSCode because with the efforts of the community, the VSCode team may consider upgrading the kernel to Electron 25+ in 1.82 or 1.83
I have provided you with the installation package, first you install VSCode, then install vscode-runme and then see the result. . .

**Comment by sourishkrout** [comment]
VS Code exploration builds (irregular unstable channel) are far ahead of `Insiders` and `Stable` VS Code periodic release channels.

We are sorry, but we can't consider this a bug unless reproducible in `Insiders`. This is likely a side-effect where many fundamental features are "broken", due to an ongoing much lower-level effort by the VS Code team.

We can consider reopening the issue if it's reproducible in `Insiders`. Hopefully it won't come so far.
